### PR TITLE
PrivDrop::default().apply() should always succeed

### PR DESCRIPTION
**Pull request by Freaky**
It seems natural to conditionally feed configuration options to a PrivDrop, and to expect `apply()` to be a no-op if no privilege changes were actually requested.

This makes it so.

### CODE REVIEW

**Comment by jedisct1** [comment]
Can we keep calling `preload()` before emitting any possible error, and even if we don't `chroot()`?

**Comment by Freaky** [comment]
I understand doing it in the context of a pending chroot, because you're about to lose access to translation files and timezone data, not sure I see why it's needed for user/group changes too?

**Comment by jedisct1** [comment]
Consistency. Applications are not expected to behave differently if a `chroot` setting is set or not.

**Comment by Freaky** [comment]
I'd fully expect an application to lose locale support in an empty chroot, I wouldn't expect it if I just switched users, or, indeed, didn't use any privdrop-related options.

I specifically made chroot a feature flag in clap-permission-flag because it implied greater behaviour changes than just switching user which not every app might support.

**Comment by jedisct1** [comment]
I'd prefer to keep the current behavior.

**Comment by Freaky** [comment]
Er, the current behaviour is annoying.  It means users have to do things like:

```rust
if opt.priv.user.is_some() || opt.priv.group.is_some() || opt.priv.chroot.is_some() {
    opt.priv.drop()?;
}
```

If you'd rather I revert the preload bit that's fine.

**Pull request closed without merging**
